In [ ]:
import numpy as np
import time
import torch
from transformers import LlamaForCausalLM, LlamaTokenizer
model_path = "/dataset/crosspipe/OriginModel/Llama-2-7b-chat-hf/"
 
device = "cuda:2" if torch.cuda.is_available() else "cpu"
tokenizer = LlamaTokenizer.from_pretrained(model_path)
model = LlamaForCausalLM.from_pretrained(model_path, device_map=device)
for use_cache in ( False,True):
  times = []
  for _ in range(1):  # measuring 10 generations
      start = time.time()
      input = tokenizer("What is KV caching?", return_tensors="pt").to(device)
      outputs = model.generate(**input, use_cache=use_cache, max_new_tokens=1000, temperature=0.00001)
      times.append(time.time() - start)
      print(outputs)
  print(f"{'With' if use_cache else 'Without'} KV caching: {round(np.mean(times), 3)} +- {round(np.std(times), 3)} seconds")

tensor([[    1,  1724,   338,   476, 29963, 22488, 29973,    13,    13, 29968,
         29963, 22488,   338,   263, 11043,  1304,   297,  7047,  5849,   304,
         11157,   278,  4180,   310,  8324,   491, 15446, 13672, 20592,   848,
           297,   263,  7090, 29889,   476, 29963, 15028,   363,   376,  1989,
         29899,  1767,  1699,   607, 14637,   304,   278,  1134,   310,   848,
          6087,   297,   278,  7090, 29889,    13,    13,   797,   263,   476,
         29963,  7090, 29892,   848,   338,  6087,   408,   263,  5101,   310,
           263,  1820,   322,   263,   995, 29889,   450,  1820,   338,  1304,
           304, 12439,   278,   848, 29892,   322,   278,   995,   338,   278,
           848,  3528, 29889,   450,  7090,   338, 12234,  8762,   408,   263,
           848,  3829, 29892,  1316,   408,   263,  6608,  1591,   470,   263,
          5447, 29892,   393,  6511,   363,  8543,  1106, 14340,   322, 11217,
           310,   278,  6087,   848, 29889,    13,    13, 29968, 29963, 22488,
           338, 15574,  1304,   297,  1856,  8324,   304, 11157,   278,  4180,
           310,  2566,  9365, 29889,  8669,   310,  2346,   292,   278,  2566,
           363,  1432,  2009, 29892,   278,  2280,   508,   671,   278,   476,
         29963,  7090,   304,  3787, 13672, 20592,   848, 29892,  1316,   408,
          1404,  4867,  2472,   470, 13672, 20592,  6515, 29889,   910, 26830,
           278,  1353,   310,  2566,  9365, 29892,   607,   508, 11157,   278,
          2280, 29915, 29879,  4180,   322,  8716,  3097, 29889,    13,    13,
         29968, 29963, 22488,   508,   884,   367,  1304,   297,   916, 10161,
           310,  7047,  5849, 29892,  1316,   408, 29901,    13,    13, 29930,
           315,  9733, 13672, 20592,   848,   297,   263,  1856,  2280,   304,
         10032,   278,  1353,   310,  2566,  9365, 29889,    13, 29930,   624,
          8253, 15562, 29892,  1316,   408,  1404,  5821,  2063,   470,  2740,
          4955, 29892,   297,   263,  7090,   304, 11157,   278,  4180,   310,
           263,  1856,  2280, 29889,    13, 29930,   315,  9733, 13672, 20592,
           848,   297,   263, 13235,  1788,   304, 10032,   278,  2254,   373,
           278,  1788,   322, 11157,   967,  8716,  3097, 29889,    13,    13,
           797, 15837, 29892,   476, 29963, 22488,   338,   263, 11043,  1304,
           304, 11157,   278,  4180,   310,  8324,   491, 15446, 13672, 20592,
           848,   297,   263,  7090, 29889,   739,   338, 15574,  1304,   297,
          1856,  8324,   304, 10032,   278,  1353,   310,  2566,  9365, 29892,
           541,   508,   884,   367,  1304,   297,   916, 10161,   310,  7047,
          5849,   304, 11157,  4180,   322,  8716,  3097, 29889,     2]],
       device='cuda:2')
With KV caching: 18.327 +- 0.0 seconds
tensor([[    1,  1724,   338,   476, 29963, 22488, 29973,    13,    13, 29968,
         29963, 22488,   338,   263, 11043,  1304,   297,  7047,  5849,   304,
         11157,   278,  4180,   310,  8324,   491, 15446, 13672, 20592,   848,
           297,   263,  7090, 29889,   476, 29963, 15028,   363,   376,  1989,
         29899,  1767,  1699,   607, 14637,   304,   278,  1134,   310,   848,
          6087,   297,   278,  7090, 29889,    13,    13,   797,   263,   476,
         29963,  7090, 29892,   848,   338,  6087,   408,   263,  5101,   310,
           263,  1820,   322,   263,   995, 29889,   450,  1820,   338,  1304,
           304, 12439,   278,   848, 29892,   322,   278,   995,   338,   278,
           848,  3528, 29889,   450,  7090,   338, 12234,  8762,   408,   263,
           848,  3829, 29892,  1316,   408,   263,  6608,  1591,   470,   263,
          5447, 29892,   393,  6511,   363,  8543,  1106, 14340,   322, 11217,
           310,   278,  6087,   848, 29889,    13,    13, 29968, 29963, 22488,
           338, 15574,  1304,   297,  1856,  8324,   304, 11157,   278,  4180,
           310,  2566,  9365, 29889,  8669,   310,  2346,   292,   278,  2566,
           363,  1432,  2009, 29892,   278,  2280,   508,   671,   278,   476,
         29963,  7090,   304,  3787, 13672, 20592,   848, 29892,  1316,   408,
          1404,  4867,  2472,   470, 13672, 20592,  6515, 29889,   910, 26830,
           278,  1353,   310,  2566,  9365, 29892,   607,   508, 11157,   278,
          2280, 29915, 29879,  4180,   322,  8716,  3097, 29889,    13,    13,
         29968, 29963, 22488,   508,   884,   367,  1304,   297,   916, 10161,
           310,  7047,  5849, 29892,  1316,   408, 29901,    13,    13, 29930,
           315,  9733, 13672, 20592,   848,   297,   263,  1856,  2280,   304,
         10032,   278,  1353,   310,  2566,  9365, 29889,    13, 29930,   624,
          8253, 15562, 29892,  1316,   408,  1404,  5821,  2063,   470,  2740,
          4955, 29892,   297,   263,  7090,   304, 11157,   278,  4180,   310,
           263,  1856,  2280, 29889,    13, 29930,   315,  9733, 13672, 20592,
           848,   297,   263, 13235,  1788,   304, 10032,   278,  2254,   373,
           278,  1788,   322, 11157,   967,  8716,  3097, 29889,    13,    13,
           797, 15837, 29892,   476, 29963, 22488,   338,   263, 11043,  1304,
           304, 11157,   278,  4180,   310,  8324,   491, 15446, 13672, 20592,
           848,   297,   263,  7090, 29889,   739,   338, 15574,  1304,   297,
          1856,  8324,   304, 10032,   278,  1353,   310,  2566,  9365, 29892,
           541,   508,   884,   367,  1304,   297,   916, 10161,   310,  7047,
          5849,   304, 11157,  4180,   322,  8716,  3097, 29889,     2]],
       device='cuda:2')
Without KV caching: 80.208 +- 0.0 seconds

tensor([[    1,  1724,   338,   476, 29963, 22488, 29973,    13,    13, 29968,
         29963, 22488,   338,   263, 11043,  1304,   297,  7047,  5849,   304,
         11157,   278,  4180,   310,  8324,   491, 15446, 13672, 20592,   848,
           297,   263,  7090, 29889,   476, 29963, 15028,   363,   376,  1989,
         29899,  1767,  1699,   607, 14637,   304,   278,  1134,   310,   848,
          6087,   297,   278,  7090, 29889,    13,    13,   797,   263,   476,
         29963,  7090, 29892,   848,   338,  6087,   408,   263,  5101,   310,
           263,  1820,   322,   263,   995, 29889,   450,  1820,   338,  1304,
           304, 12439,   278,   848, 29892,   322,   278,   995,   338,   278,
           848,  3528, 29889,   450,  7090,   338, 12234,  8762,   408,   263,
           848,  3829, 29892,  1316,   408,   263,  6608,  1591,   470,   263,
          5447, 29892,   393,  6511,   363,  8543,  1106, 14340,   322, 11217,
           310,   278,  6087,   848, 29889,    13,    13, 29968, 29963, 22488,
           338, 15574,  1304,   297,  1856,  8324,   304, 11157,   278,  4180,
           310,  2566,  9365, 29889,  8669,   310,  2346,   292,   278,  2566,
           363,  1432,  2009, 29892,   278,  2280,   508,   671,   278,   476,
         29963,  7090,   304,  3787, 13672, 20592,   848, 29892,  1316,   408,
          1404,  4867,  2472,   470, 13672, 20592,  6515, 29889,   910, 26830,
           278,  1353,   310,  2566,  9365, 29892,   607,   508, 11157,   278,
          2280, 29915, 29879,  4180,   322,  8716,  3097, 29889,    13,    13,
         29968, 29963, 22488,   508,   884,   367,  1304,   297,   916, 10161,
           310,  7047,  5849, 29892,  1316,   408, 29901,    13,    13, 29930,
           315,  9733, 13672, 20592,   848,   297,   263,  1856,  2280,   304,
         10032,   278,  1353,   310,  2566,  9365, 29889,    13, 29930,   624,
          8253, 15562, 29892,  1316,   408,  1404,  5821,  2063,   470,  2740,
...
           541,   508,   884,   367,  1304,   297,   916, 10161,   310,  7047,
          5849,   304, 11157,  4180,   322,  8716,  3097, 29889,     2]],
       device='cuda:2')
With KV caching: 17.642 +- 0.0 seconds
Output is truncated. View as a scrollable element or open in a text editor. Adjust cell output settings...

In [ ]:
import numpy as np
import time
import torch
from transformers import LlamaForCausalLM, LlamaTokenizer
model_path = "/dataset/crosspipe/OriginModel/Llama-2-7b-chat-hf/"
device = "cuda:2" if torch.cuda.is_available() else "cpu"
model = LlamaForCausalLM.from_pretrained(model_path, device_map=device)
tokenizer = LlamaTokenizer.from_pretrained(model_path)

In [ ]:
tokenizer.__class__

In [ ]:
tokenizer.pad_token = tokenizer.pad_token

In [47]:
input_texts = [
    "please tell me What is KV caching?",
    "what can i do to help you to do something?"
]
inputs = tokenizer(input_texts,truncation=True,padding=True,max_length=256,return_tensors="pt").to(device)

In [48]:
generated_ids = model.generate(**inputs, max_new_tokens=1000)

In [46]:
decoded_output = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)

print(decoded_output)

['请告诉我 KV 缓存是什么？\n\nKV 缓存是一种基于内存的缓存系统，它通常用于存储大量的键值对，以提高系统的性能和可扩展性。KV 缓存通常用于存储快速访问的数据，例如用户 Session 信息、缓存、历史记录等。\nKV 缓存的主要特点是：\n1. 高性能：KV 缓存通常使用内存作为存储方式，因此它可以提供非常快的访问速度，比如读取和写入操作。\n2. 低延迟：KV 缓存通常具有低延迟的特点，因为它可以直接从内存中读取和写入数据，而不需要进行磁盘IO等操作。\n3. 高可扩展性：KV 缓存可以轻松地扩展，因为它可以通过添加更多的内存来提高性能。\n4. 低成本：KV 缓存通常具有低成本的特点，因为它可以使用内存作为存储方式，而不需要购买和维护较昂贵的磁盘等设备。\n5. 安全性：KV 缓存通常具有高度的安全性，因为它可以使用加密和权限控制来保护数据的安全性。\n6. 可扩展性：KV 缓存可以轻松地扩展，因为它可以通过添加更多的内存来提高性能。\n7. 可靠性：KV 缓存通常具有高度的可靠性，因为它可以通过多个内存节点来保证数据的可靠性。\n\n在实际应用中，KV 缓存通常用于各种场景，例如：\n1. 缓存：KV 缓存可以用于缓存快速访问的数据，例如用户 Session 信息、缓存、历史记录等。\n2. 数据存储：KV 缓存可以用于存储大量的键值对，例如数据库、缓存、历史记录等。\n3. 消息队列：KV 缓存可以用于实现消息队列功能，例如在 Web 应用中实现消息队列功能。\n4. 分布式系统：KV 缓存可以用于实现分布式系统的功能，例如在分布式文件系统中实现分布式文件系统的功能。\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\

In [ ]:
inputs

In [ ]:
generated_ids = model.generate(**inputs, max_new_tokens=1000)

In [44]:
input_texts = ["请告诉我 KV 缓存是什么？", "我可以做些什么来帮助你？"]
inputs = tokenizer(input_texts, padding=True, truncation=True,max_length=256, return_tensors="pt").to('cuda:2')
tokenizer.pad_token = tokenizer.eos_token
# 使用模型生成文本
generated_ids = model.generate(**inputs, max_new_tokens=1000)

# 解码生成的 token ID
decoded_output = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)

print(decoded_output)

['请告诉我 KV 缓存是什么？\n\nKV 缓存是一种基于内存的缓存系统，它通常用于存储大量的键值对，以提高系统的性能和可扩展性。KV 缓存通常用于存储快速访问的数据，例如用户 Session 信息、缓存、历史记录等。\nKV 缓存的主要特点是：\n1. 高性能：KV 缓存通常使用内存作为存储方式，因此它可以提供非常快的访问速度，比如读取和写入操作。\n2. 低延迟：KV 缓存通常具有低延迟的特点，因为它可以直接从内存中读取和写入数据，而不需要进行磁盘IO等操作。\n3. 高可扩展性：KV 缓存可以轻松地扩展，因为它可以通过添加更多的内存来提高性能。\n4. 低成本：KV 缓存通常具有低成本的特点，因为它可以使用内存作为存储方式，而不需要购买和维护较昂贵的磁盘等设备。\n5. 安全性：KV 缓存通常具有高度的安全性，因为它可以使用加密和权限控制来保护数据的安全性。\n6. 可扩展性：KV 缓存可以轻松地扩展，因为它可以通过添加更多的内存来提高性能。\n7. 可靠性：KV 缓存通常具有高度的可靠性，因为它可以通过多个内存节点来保证数据的可靠性。\n\n在实际应用中，KV 缓存通常用于各种场景，例如：\n1. 缓存：KV 缓存可以用于缓存快速访问的数据，例如用户 Session 信息、缓存、历史记录等。\n2. 数据存储：KV 缓存可以用于存储大量的键值对，例如数据库、缓存、历史记录等。\n3. 消息队列：KV 缓存可以用于实现消息队列功能，例如在 Web 应用中实现消息队列功能。\n4. 分布式系统：KV 缓存可以用于实现分布式系统的功能，例如在分布式文件系统中实现分布式文件系统的功能。\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\

### Another way to decode❤


In [ ]:
generated_ids = generated_ids.tolist()

# 解码每一行
decoded_texts = [tokenizer.decode(ids, skip_special_tokens=True) for ids in generated_ids]

# 打印解码后的文本
for text in decoded_texts:
    print(text)

In [ ]:
generated_text = tokenizer.decode(generated_ids, skip_special_tokens=True)
generated_text

In [ ]:
tokenizer.pad_token = tokenizer.eos_token

In [ ]:
import numpy as np
import time
import torch
from transformers import LlamaForCausalLM, LlamaTokenizer
model_path = "/dataset/crosspipe/OriginModel/Llama-2-7b-chat-hf/"
device = "cuda:2" if torch.cuda.is_available() else "cpu"
model = LlamaForCausalLM.from_pretrained(model_path, device_map=device)
tokenizer = LlamaTokenizer.from_pretrained(model_path)


In [49]:
input = "What is KV caching ?"
inputs = tokenizer(input, return_tensors="pt").to(device)

In [51]:
outputs = model.generate(**inputs)
tokenizer.batch_decode(outputs, skip_special_tokens=True)

TypeError: int() argument must be a string, a bytes-like object or a real number, not 'list'

In [ ]:
outputs