In [11]:
import numpy as np
import time
import torch
from transformers import LlamaForCausalLM, LlamaTokenizer
model_path = "/dataset/crosspipe/OriginModel/Llama-2-7b-chat-hf/"
 
device = "cuda:2" if torch.cuda.is_available() else "cpu"
tokenizer = LlamaTokenizer.from_pretrained(model_path)
model = LlamaForCausalLM.from_pretrained(model_path, device_map=device)
for use_cache in ( False,True):
  times = []
  for _ in range(1):  # measuring 10 generations
      start = time.time()
      input = tokenizer("What is KV caching?", return_tensors="pt").to(device)
      outputs = model.generate(**input, use_cache=use_cache, max_new_tokens=1000, temperature=0.00001)
      times.append(time.time() - start)
      print(outputs)
  print(f"{'With' if use_cache else 'Without'} KV caching: {round(np.mean(times), 3)} +- {round(np.std(times), 3)} seconds")

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

OutOfMemoryError: CUDA out of memory. Tried to allocate 172.00 MiB. GPU 2 has a total capacity of 31.74 GiB of which 21.12 MiB is free. Process 1490337 has 30.93 GiB memory in use. Process 1591256 has 808.00 MiB memory in use. Of the allocated memory 500.02 MiB is allocated by PyTorch, and 1.98 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

tensor([[    1,  1724,   338,   476, 29963, 22488, 29973,    13,    13, 29968,
         29963, 22488,   338,   263, 11043,  1304,   297,  7047,  5849,   304,
         11157,   278,  4180,   310,  8324,   491, 15446, 13672, 20592,   848,
           297,   263,  7090, 29889,   476, 29963, 15028,   363,   376,  1989,
         29899,  1767,  1699,   607, 14637,   304,   278,  1134,   310,   848,
          6087,   297,   278,  7090, 29889,    13,    13,   797,   263,   476,
         29963,  7090, 29892,   848,   338,  6087,   408,   263,  5101,   310,
           263,  1820,   322,   263,   995, 29889,   450,  1820,   338,  1304,
           304, 12439,   278,   848, 29892,   322,   278,   995,   338,   278,
           848,  3528, 29889,   450,  7090,   338, 12234,  8762,   408,   263,
           848,  3829, 29892,  1316,   408,   263,  6608,  1591,   470,   263,
          5447, 29892,   393,  6511,   363,  8543,  1106, 14340,   322, 11217,
           310,   278,  6087,   848, 29889,    13,    13, 29968, 29963, 22488,
           338, 15574,  1304,   297,  1856,  8324,   304, 11157,   278,  4180,
           310,  2566,  9365, 29889,  8669,   310,  2346,   292,   278,  2566,
           363,  1432,  2009, 29892,   278,  2280,   508,   671,   278,   476,
         29963,  7090,   304,  3787, 13672, 20592,   848, 29892,  1316,   408,
          1404,  4867,  2472,   470, 13672, 20592,  6515, 29889,   910, 26830,
           278,  1353,   310,  2566,  9365, 29892,   607,   508, 11157,   278,
          2280, 29915, 29879,  4180,   322,  8716,  3097, 29889,    13,    13,
         29968, 29963, 22488,   508,   884,   367,  1304,   297,   916, 10161,
           310,  7047,  5849, 29892,  1316,   408, 29901,    13,    13, 29930,
           315,  9733, 13672, 20592,   848,   297,   263,  1856,  2280,   304,
         10032,   278,  1353,   310,  2566,  9365, 29889,    13, 29930,   624,
          8253, 15562, 29892,  1316,   408,  1404,  5821,  2063,   470,  2740,
          4955, 29892,   297,   263,  7090,   304, 11157,   278,  4180,   310,
           263,  1856,  2280, 29889,    13, 29930,   315,  9733, 13672, 20592,
           848,   297,   263, 13235,  1788,   304, 10032,   278,  2254,   373,
           278,  1788,   322, 11157,   967,  8716,  3097, 29889,    13,    13,
           797, 15837, 29892,   476, 29963, 22488,   338,   263, 11043,  1304,
           304, 11157,   278,  4180,   310,  8324,   491, 15446, 13672, 20592,
           848,   297,   263,  7090, 29889,   739,   338, 15574,  1304,   297,
          1856,  8324,   304, 10032,   278,  1353,   310,  2566,  9365, 29892,
           541,   508,   884,   367,  1304,   297,   916, 10161,   310,  7047,
          5849,   304, 11157,  4180,   322,  8716,  3097, 29889,     2]],
       device='cuda:2')
With KV caching: 18.327 +- 0.0 seconds
tensor([[    1,  1724,   338,   476, 29963, 22488, 29973,    13,    13, 29968,
         29963, 22488,   338,   263, 11043,  1304,   297,  7047,  5849,   304,
         11157,   278,  4180,   310,  8324,   491, 15446, 13672, 20592,   848,
           297,   263,  7090, 29889,   476, 29963, 15028,   363,   376,  1989,
         29899,  1767,  1699,   607, 14637,   304,   278,  1134,   310,   848,
          6087,   297,   278,  7090, 29889,    13,    13,   797,   263,   476,
         29963,  7090, 29892,   848,   338,  6087,   408,   263,  5101,   310,
           263,  1820,   322,   263,   995, 29889,   450,  1820,   338,  1304,
           304, 12439,   278,   848, 29892,   322,   278,   995,   338,   278,
           848,  3528, 29889,   450,  7090,   338, 12234,  8762,   408,   263,
           848,  3829, 29892,  1316,   408,   263,  6608,  1591,   470,   263,
          5447, 29892,   393,  6511,   363,  8543,  1106, 14340,   322, 11217,
           310,   278,  6087,   848, 29889,    13,    13, 29968, 29963, 22488,
           338, 15574,  1304,   297,  1856,  8324,   304, 11157,   278,  4180,
           310,  2566,  9365, 29889,  8669,   310,  2346,   292,   278,  2566,
           363,  1432,  2009, 29892,   278,  2280,   508,   671,   278,   476,
         29963,  7090,   304,  3787, 13672, 20592,   848, 29892,  1316,   408,
          1404,  4867,  2472,   470, 13672, 20592,  6515, 29889,   910, 26830,
           278,  1353,   310,  2566,  9365, 29892,   607,   508, 11157,   278,
          2280, 29915, 29879,  4180,   322,  8716,  3097, 29889,    13,    13,
         29968, 29963, 22488,   508,   884,   367,  1304,   297,   916, 10161,
           310,  7047,  5849, 29892,  1316,   408, 29901,    13,    13, 29930,
           315,  9733, 13672, 20592,   848,   297,   263,  1856,  2280,   304,
         10032,   278,  1353,   310,  2566,  9365, 29889,    13, 29930,   624,
          8253, 15562, 29892,  1316,   408,  1404,  5821,  2063,   470,  2740,
          4955, 29892,   297,   263,  7090,   304, 11157,   278,  4180,   310,
           263,  1856,  2280, 29889,    13, 29930,   315,  9733, 13672, 20592,
           848,   297,   263, 13235,  1788,   304, 10032,   278,  2254,   373,
           278,  1788,   322, 11157,   967,  8716,  3097, 29889,    13,    13,
           797, 15837, 29892,   476, 29963, 22488,   338,   263, 11043,  1304,
           304, 11157,   278,  4180,   310,  8324,   491, 15446, 13672, 20592,
           848,   297,   263,  7090, 29889,   739,   338, 15574,  1304,   297,
          1856,  8324,   304, 10032,   278,  1353,   310,  2566,  9365, 29892,
           541,   508,   884,   367,  1304,   297,   916, 10161,   310,  7047,
          5849,   304, 11157,  4180,   322,  8716,  3097, 29889,     2]],
       device='cuda:2')
Without KV caching: 80.208 +- 0.0 seconds

tensor([[    1,  1724,   338,   476, 29963, 22488, 29973,    13,    13, 29968,
         29963, 22488,   338,   263, 11043,  1304,   297,  7047,  5849,   304,
         11157,   278,  4180,   310,  8324,   491, 15446, 13672, 20592,   848,
           297,   263,  7090, 29889,   476, 29963, 15028,   363,   376,  1989,
         29899,  1767,  1699,   607, 14637,   304,   278,  1134,   310,   848,
          6087,   297,   278,  7090, 29889,    13,    13,   797,   263,   476,
         29963,  7090, 29892,   848,   338,  6087,   408,   263,  5101,   310,
           263,  1820,   322,   263,   995, 29889,   450,  1820,   338,  1304,
           304, 12439,   278,   848, 29892,   322,   278,   995,   338,   278,
           848,  3528, 29889,   450,  7090,   338, 12234,  8762,   408,   263,
           848,  3829, 29892,  1316,   408,   263,  6608,  1591,   470,   263,
          5447, 29892,   393,  6511,   363,  8543,  1106, 14340,   322, 11217,
           310,   278,  6087,   848, 29889,    13,    13, 29968, 29963, 22488,
           338, 15574,  1304,   297,  1856,  8324,   304, 11157,   278,  4180,
           310,  2566,  9365, 29889,  8669,   310,  2346,   292,   278,  2566,
           363,  1432,  2009, 29892,   278,  2280,   508,   671,   278,   476,
         29963,  7090,   304,  3787, 13672, 20592,   848, 29892,  1316,   408,
          1404,  4867,  2472,   470, 13672, 20592,  6515, 29889,   910, 26830,
           278,  1353,   310,  2566,  9365, 29892,   607,   508, 11157,   278,
          2280, 29915, 29879,  4180,   322,  8716,  3097, 29889,    13,    13,
         29968, 29963, 22488,   508,   884,   367,  1304,   297,   916, 10161,
           310,  7047,  5849, 29892,  1316,   408, 29901,    13,    13, 29930,
           315,  9733, 13672, 20592,   848,   297,   263,  1856,  2280,   304,
         10032,   278,  1353,   310,  2566,  9365, 29889,    13, 29930,   624,
          8253, 15562, 29892,  1316,   408,  1404,  5821,  2063,   470,  2740,
...
           541,   508,   884,   367,  1304,   297,   916, 10161,   310,  7047,
          5849,   304, 11157,  4180,   322,  8716,  3097, 29889,     2]],
       device='cuda:2')
With KV caching: 17.642 +- 0.0 seconds
Output is truncated. View as a scrollable element or open in a text editor. Adjust cell output settings...

In [ ]:
import numpy as np
import time
import torch
from transformers import LlamaForCausalLM, LlamaTokenizer
model_path = "/dataset/crosspipe/OriginModel/Llama-2-7b-chat-hf/"
device = "cuda:3" if torch.cuda.is_available() else "cpu"
model = LlamaForCausalLM.from_pretrained(model_path, device_map=device)
tokenizer = LlamaTokenizer.from_pretrained(model_path)

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

In [ ]:
tokenizer.__class__

transformers.models.llama.tokenization_llama.LlamaTokenizer

In [ ]:
tokenizer.pad_token = tokenizer.eos_token

In [ ]:
input_texts = [
    "please tell me What is KV caching?",
    "what can i do to help you to do something?"
]
inputs = tokenizer(input_texts,truncation=True,padding=True,max_length=256,return_tensors="pt").to(device)

In [ ]:
inputs

{'input_ids': tensor([[    1,  3113,  2649,   592,  1724,   338,   476, 29963, 22488, 29973,
             2,     2],
        [    1,   825,   508,   474,   437,   304,  1371,   366,   304,   437,
          1554, 29973]], device='cuda:3'), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], device='cuda:3')}

In [ ]:
generated_ids = model.generate(**inputs, max_new_tokens=1000)
decoded_output = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)
print(decoded_output)

['please tell me What is KV caching?s\n\nKV caching is a mechanism for storing data in a key-value store, which is a type of data structure that stores data as a collection of key-value pairs. The key-value pairs are typically stored in a distributed database or a distributed cache, which allows for efficient retrieval and update of the data.\nKV caching is commonly used in web applications to improve performance by reducing the number of database queries required to retrieve data. For example, a web application might use KV caching to store frequently accessed data, such as user preferences or session data, in a cache rather than retrieving it from the database every time it is needed. This can significantly reduce the load on the database and improve the overall performance of the application.\nKV caching can be implemented using a variety of technologies, including:\n1. Redis: A popular open-source key-value store that provides a fast, in-memory data structure for storing and retrie

### Another way to decode❤


In [12]:
generated_ids = generated_ids.tolist()

# 解码每一行
decoded_texts = [tokenizer.decode(ids, skip_special_tokens=True) for ids in generated_ids]

# 打印解码后的文本
for text in decoded_texts:
    print(text)

please tell me What is KV caching?s

KV caching is a mechanism for storing data in a key-value store, which is a type of data structure that stores data as a collection of key-value pairs. The key-value pairs are typically stored in a distributed database or a distributed cache, which allows for efficient retrieval and update of the data.
KV caching is commonly used in web applications to improve performance by reducing the number of database queries required to retrieve data. For example, a web application might use KV caching to store frequently accessed data, such as user preferences or session data, in a cache rather than retrieving it from the database every time it is needed. This can significantly reduce the load on the database and improve the overall performance of the application.
KV caching can be implemented using a variety of technologies, including:
1. Redis: A popular open-source key-value store that provides a fast, in-memory data structure for storing and retrieving da

In [14]:
generated_text = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)
generated_text

['please tell me What is KV caching?s\n\nKV caching is a mechanism for storing data in a key-value store, which is a type of data structure that stores data as a collection of key-value pairs. The key-value pairs are typically stored in a distributed database or a distributed cache, which allows for efficient retrieval and update of the data.\nKV caching is commonly used in web applications to improve performance by reducing the number of database queries required to retrieve data. For example, a web application might use KV caching to store frequently accessed data, such as user preferences or session data, in a cache rather than retrieving it from the database every time it is needed. This can significantly reduce the load on the database and improve the overall performance of the application.\nKV caching can be implemented using a variety of technologies, including:\n1. Redis: A popular open-source key-value store that provides a fast, in-memory data structure for storing and retrie