In [1]:
import torch 
x = torch.tensor([1, 2, 3, 4])

In [26]:
a = torch.rand(1,4)

In [27]:
a

tensor([[0.6707, 0.6909, 0.1247, 0.0702]])

In [2]:
x.shape

torch.Size([4])

In [7]:
b = x.unsqueeze(0)

In [8]:
b

tensor([[1, 2, 3, 4]])

In [46]:
x = torch.randn(2, 1,3, 4)

In [47]:
x

tensor([[[[ 0.2314,  0.3324, -0.4524,  1.0608],
          [ 1.5179,  0.5587,  0.1939, -0.4904],
          [ 0.8371, -0.0078,  0.0797, -0.5254]]],


        [[[-0.8521,  0.2102, -0.2936, -0.0965],
          [ 1.3862, -1.5915,  0.8465,  1.4526],
          [ 0.6005,  0.4831,  1.7623, -1.7082]]]])

In [48]:
x.squeeze(1)

tensor([[[ 0.2314,  0.3324, -0.4524,  1.0608],
         [ 1.5179,  0.5587,  0.1939, -0.4904],
         [ 0.8371, -0.0078,  0.0797, -0.5254]],

        [[-0.8521,  0.2102, -0.2936, -0.0965],
         [ 1.3862, -1.5915,  0.8465,  1.4526],
         [ 0.6005,  0.4831,  1.7623, -1.7082]]])

In [54]:
b = x.squeeze(1)

In [55]:
b.shape

torch.Size([2, 3, 4])

In [56]:
b.unsqueeze(2).shape

torch.Size([2, 3, 1, 4])

: 