In [1]:
import torch

x = torch.tensor([[1.0, 3.0, 2.0], [4.0, 6.0, 5.0]])


In [8]:
tmp_sum = torch.sum(x, dim=-2)

In [9]:
tmp_sum

tensor([5., 9., 7.])

In [2]:
x

tensor([[1., 3., 2.],
        [4., 6., 5.]])

In [5]:
values, indices = x.topk(k=2, dim=0)

In [6]:
values

tensor([[4., 6., 5.],
        [1., 3., 2.]])

In [7]:
indices

tensor([[1, 1, 1],
        [0, 0, 0]])