In [16]:
import torch

mask = torch.full((3, 3), torch.finfo(torch.float16).min, device="cpu")


In [17]:
mask

tensor([[-65504., -65504., -65504.],
        [-65504., -65504., -65504.],
        [-65504., -65504., -65504.]])

In [18]:
mask_cond = torch.arange(mask.size(-1))

In [19]:
mask_cond + 1

tensor([1, 2, 3])

In [20]:
(mask_cond + 1).view(mask.size(-1), 1)

tensor([[1],
        [2],
        [3]])

In [21]:
mask_cond < (mask_cond + 1).view(mask.size(-1), 1)

tensor([[ True, False, False],
        [ True,  True, False],
        [ True,  True,  True]])

In [23]:
mask.masked_fill_(mask_cond < (mask_cond + 1).view(mask.size(-1), 1),0)

tensor([[     0., -65504., -65504.],
        [     0.,      0., -65504.],
        [     0.,      0.,      0.]])