In [3]:
import torch

In [21]:
def sanity_check(mask):
    # mask (head, query, key)
    ones = torch.ones_like(mask)
    print(ones)
    ones = torch.triu(ones, diagonal=0)
    # torch.tril(input, diagonal=0)的作用是返回一个tensor，其上三角部分被置零，其余部分不变
    # torch.triu(input, diagonal=0)的作用是返回一个tensor，其下三角部分被置零，其余部分不变
    print(ones)
    mask_bottom = torch.logical_or(mask, ones)
    #torch.logical_or(a,b)的作用是对a和b逐元素进行逻辑或操作，返回一个新的tensor
    mask_bottom = mask_bottom.squeeze(0)
    print(mask_bottom)
    error_cnt = 0
    for i in range(mask_bottom.shape[1]-1):
        index = mask_bottom[:,i,:].eq(0).unsqueeze(1)
        index[:,i:]=0
        error_cnt += (mask_bottom[:,i:,:] * index).sum().item()
    print(error_cnt)
    return error_cnt

In [26]:
# Example mask (head, query, key)
mask = torch.tensor([[[0, 1, 0],
                      [0, 0, 1],
                      [0, 0, 0]]])

# Call sanity_check
mask_bottom = sanity_check(mask)
mask_bottom.shape[2]

tensor([[[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]]])
tensor([[[1, 0, 0],
         [1, 1, 0],
         [1, 1, 1]]])
tensor([[ True,  True, False],
        [ True,  True,  True],
        [ True,  True,  True]])


AttributeError: 'NoneType' object has no attribute 'shape'